class CfgPatches {
    class O_Taliban_2002 {
        units[] = {
            "O_Taliban_S1203_Van_2002_01",
            "O_Taliban_Ural_4320_2002_01",
            "O_Taliban_Insurgent_AKMN_2002_01",
            "O_Taliban_Insurgent_AKMS_2002_01",
            "O_Taliban_Insurgent_AK74_2002_01",
            "O_Taliban_Insurgent_AKM_2002_01",
            "O_Taliban_Insurgent_SMLE_2002_01",
            "O_Taliban_Insurgent_PKM_2002_01",
            "O_Taliban_Insurgent_PM63_2002_01",
            "O_Taliban_Insurgent_RPG7_2002_01",
            "O_Taliban_Taliban_Leader_2002_01",
            "O_Taliban_Technical_DShKM_2002_01",
            "O_Taliban_Datsun_Technical_2002_01",
            "O_Taliban_Datsun_Technical_2002_02",
            "O_Taliban_Hilux_Technical_2002_01",
            "O_Taliban_Hilux_Technical_1_2002_01",
            "O_Taliban_T55_2002_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "rhs_c_heavyweapons"
        };
        author = "JerkinMerkin";
        authors[] = {"JerkinMerkin"};
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 182.144710 on Stable branch
// Generated with ALiVE version 1.6.1.1804271
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_Taliban_2002 {
        displayName = "Taliban (TFR)";
        side = 0;
        flag = "po_main\data\UI\flags\flag_am_opf_co.paa";
        icon = "po_main\data\UI\flags\flag_am_opf_co.paa";
        priority = 1;
    };
};

class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class walker_a3_s1203;
    class walker_a3_s1203_OCimport_01 : walker_a3_s1203 { scope = 0; class EventHandlers; };
    class walker_a3_s1203_OCimport_02 : walker_a3_s1203_OCimport_01 { scope = 0; class EventHandlers; };

    class RHS_Ural_VDV_01;
    class RHS_Ural_VDV_01_OCimport_01 : RHS_Ural_VDV_01 { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Ural_VDV_01_OCimport_02 : RHS_Ural_VDV_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_hiluxhmg;
    class walker_a3_hiluxhmg_OCimport_01 : walker_a3_hiluxhmg { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_hiluxhmg_OCimport_02 : walker_a3_hiluxhmg_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class walker_a3_datsun;
    class walker_a3_datsun_OCimport_01 : walker_a3_datsun { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_datsun_OCimport_02 : walker_a3_datsun_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_datsun_2;
    class walker_a3_datsun_2_OCimport_01 : walker_a3_datsun_2 { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_datsun_2_OCimport_02 : walker_a3_datsun_2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_hilux;
    class walker_a3_hilux_OCimport_01 : walker_a3_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_hilux_OCimport_02 : walker_a3_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_v_hilux;
    class walker_a3_v_hilux_OCimport_01 : walker_a3_v_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_v_hilux_OCimport_02 : walker_a3_v_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };


    class O_Taliban_S1203_Van_2002_01 : walker_a3_s1203_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "S1203 Van";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_AKMN_2002_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Ural_4320_2002_01 : RHS_Ural_VDV_01_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_AKMN_2002_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_kabina_civil_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\ural\data\ural_plachta_civil_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Camo3";

    };
	
	class CUP_I_TK_GUE_Soldier;
    class CUP_I_TK_GUE_Soldier_OCimport_01 : CUP_I_TK_GUE_Soldier { scope = 0; class EventHandlers; };
    class CUP_I_TK_GUE_Soldier_OCimport_02 : CUP_I_TK_GUE_Soldier_OCimport_01 { class EventHandlers; };


    class O_Taliban_Insurgent_AKMN_2002_01 : CUP_I_TK_GUE_Soldier_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (AKMN)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_Creme";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_03","CUP_H_TKI_Pakol_1_01"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_03","CUP_H_TKI_Pakol_1_01"};

        weapons[] = {"rhs_weap_akmn"};
        respawnWeapons[] = {"rhs_weap_akmn"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akmn","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"CFP_U_KhetPartug_Long_Creme",{{"rhs_mag_rgd5",1,1},{"rhs_30Rnd_762x39mm",2,30}}},{"CUP_V_OI_TKI_Jacket1_03",{{"rhs_30Rnd_762x39mm",2,30},{"rhs_mag_rgd5",1,1}}},{},"CUP_H_TKI_Pakol_1_01","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_AKMS_2002_01 : O_Taliban_Insurgent_AKMN_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (AKMS)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default"};

        uniformClass = "CFP_U_KhetPartug_Short_Grey";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket4_06","CUP_H_TKI_Lungee_Open_03"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket4_06","CUP_H_TKI_Lungee_Open_03"};

        weapons[] = {"rhs_weap_akms"};
        respawnWeapons[] = {"rhs_weap_akms"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"CFP_U_KhetPartug_Short_Grey",{{"rhs_30Rnd_762x39mm",2,30}}},{"CUP_V_OI_TKI_Jacket4_06",{{"rhs_30Rnd_762x39mm",5,30},{"rhs_mag_rgd5",1,1}}},{},"CUP_H_TKI_Lungee_Open_03","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_AK74_2002_01 : O_Taliban_Insurgent_AKMS_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (AK74)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default"};

        uniformClass = "CFP_U_KhetPartug_Long_Grey";

        linkedItems[] = {"CFP_HouthisJacket","CUP_H_TKI_Lungee_01"};
        respawnlinkedItems[] = {"CFP_HouthisJacket","CUP_H_TKI_Lungee_01"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_AK","rhs_30Rnd_545x39_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_AK","rhs_30Rnd_545x39_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_AK",30},{},""},{},{},{"CFP_U_KhetPartug_Long_Grey",{{"rhs_mag_rgd5",1,1},{"rhs_30Rnd_545x39_AK",3,30}}},{"CFP_HouthisJacket",{{"rhs_30Rnd_545x39_AK",3,30}}},{},"CUP_H_TKI_Lungee_01","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_AKM_2002_01 : O_Taliban_Insurgent_AKMN_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (AKM)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_01";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_01","CUP_H_TKI_Lungee_Open_04"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_01","CUP_H_TKI_Lungee_Open_04"};

        weapons[] = {"rhs_weap_akm"};
        respawnWeapons[] = {"rhs_weap_akm"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"CUP_O_TKI_Khet_Partug_01",{{"rhs_mag_rgd5",1,1},{"rhs_30Rnd_762x39mm",2,30}}},{"CUP_V_OI_TKI_Jacket1_01",{}},{},"CUP_H_TKI_Lungee_Open_04","CFP_Beard",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_SMLE_2002_01 : O_Taliban_Insurgent_AKM_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (SMLE)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Short_BlueGrey";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket4_01","CUP_H_TKI_Pakol_2_01"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket4_01","CUP_H_TKI_Pakol_2_01"};

        weapons[] = {"CUP_srifle_LeeEnfield"};
        respawnWeapons[] = {"CUP_srifle_LeeEnfield"};

        magazines[] = {"CUP_10x_303_M","CUP_10x_303_M"};
        respawnMagazines[] = {"CUP_10x_303_M","CUP_10x_303_M"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_LeeEnfield","","","",{"CUP_10x_303_M",10},{},""},{},{},{"CFP_U_KhetPartug_Short_BlueGrey",{{"CUP_10x_303_M",3,10}}},{"CUP_V_OI_TKI_Jacket4_01",{{"CUP_10x_303_M",5,10}}},{},"CUP_H_TKI_Pakol_2_01","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_PKM_2002_01 : O_Taliban_Insurgent_AKMS_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (PKM)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default"};

        uniformClass = "CFP_U_KhetPartug_Long_BlueGrey";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_03","SP_Shemagh_CheckRed"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_03","SP_Shemagh_CheckRed"};

        weapons[] = {"rhs_weap_pkm"};
        respawnWeapons[] = {"rhs_weap_pkm"};

        magazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pkm","","","",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"CFP_U_KhetPartug_Long_BlueGrey",{{"rhs_mag_rgd5",1,1}}},{"CUP_V_OI_TKI_Jacket1_03",{{"rhs_mag_rgd5",1,1}}},{},"SP_Shemagh_CheckRed","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_PM63_2002_01 : O_Taliban_Insurgent_AKMN_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (PM63)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Short_Purple";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket4_01","CUP_H_TKI_Lungee_Open_03"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket4_01","CUP_H_TKI_Lungee_Open_03"};

        weapons[] = {"rhs_weap_pm63"};
        respawnWeapons[] = {"rhs_weap_pm63"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pm63","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"CFP_U_KhetPartug_Short_Purple",{{"rhs_mag_rgd5",1,1},{"rhs_30Rnd_762x39mm",2,30}}},{"CUP_V_OI_TKI_Jacket4_01",{{"rhs_30Rnd_762x39mm",4,30},{"rhs_mag_rgd5",1,1}}},{},"CUP_H_TKI_Lungee_Open_03","CFP_Beard",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Insurgent_RPG7_2002_01 : O_Taliban_Insurgent_AKMN_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Insurgent (RPG7)";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_02";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket4_01","SP_Shemagh_CheckRed"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket4_01","SP_Shemagh_CheckRed"};

        weapons[] = {"rhs_weap_akmn","launch_RPG7_F"};
        respawnWeapons[] = {"rhs_weap_akmn","launch_RPG7_F"};

        magazines[] = {"rhs_30Rnd_762x39mm","RPG7_F","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","RPG7_F","rhs_30Rnd_762x39mm"};

        backpack = "rhs_rpg_empty";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akmn","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{"launch_RPG7_F","","","",{"RPG7_F",1},{},""},{},{"CUP_O_TKI_Khet_Partug_02",{{"rhs_mag_rgd5",1,1},{"rhs_30Rnd_762x39mm",2,30}}},{"CUP_V_OI_TKI_Jacket4_01",{{"rhs_30Rnd_762x39mm",4,30},{"rhs_mag_rgd5",1,1}}},{"rhs_rpg_empty",{{"RPG7_F",2,1}}},"SP_Shemagh_CheckRed","",{},{"","","","","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Taliban_Leader_2002_01 : O_Taliban_Insurgent_AKMS_2002_01 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Taliban Leader";
        side = 0;
        faction = "O_Taliban_2002";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_GUERIL_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_06";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket4_03","CUP_H_TKI_Pakol_2_06","ItemMap","TFAR_anprc148jem","ItemCompass"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket4_03","CUP_H_TKI_Pakol_2_06","ItemMap","TFAR_anprc148jem","ItemCompass"};

        weapons[] = {"rhs_weap_akms","Binocular"};
        respawnWeapons[] = {"rhs_weap_akms","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"CUP_O_TKI_Khet_Partug_06",{{"rhs_30Rnd_762x39mm",2,30},{"rhs_mag_rgd5",1,1}}},{"CUP_V_OI_TKI_Jacket4_03",{{"rhs_30Rnd_762x39mm",5,30},{"rhs_mag_rgd5",1,1}}},{},"CUP_H_TKI_Pakol_2_06","G_Aviator",{"Binocular","","","",{},{},""},{"ItemMap","","TFAR_anprc148jem","ItemCompass","",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Technical_DShKM_2002_01 : walker_a3_hiluxhmg_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux Technical (DShKM)";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_AKMN_2002_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Taliban_Insurgent_AK74_2002_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class CUP_I_T55_TK_GUE;
    class CUP_I_T55_TK_GUE_OCimport_01 : CUP_I_T55_TK_GUE { scope = 0; class EventHandlers; class Turrets; };
    class CUP_I_T55_TK_GUE_OCimport_02 : CUP_I_T55_TK_GUE_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };
	
	class O_Taliban_T55_2002_01: CUP_I_T55_TK_GUE
	{
		_generalMacro = "O_Taliban_T55_2002_01";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		displayName = "T-55A";
		faction = "O_Taliban_2002";
		crew = "O_Taliban_Insurgent_AKMN_2002_01";
		typicalCargo[] = {"O_Taliban_Insurgent_AKMN_2002_01"};
		};

    class O_Taliban_Datsun_Technical_2002_01 : walker_a3_datsun_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Datsun Technical";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_AKMN_2002_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_Taliban_Insurgent_SMLE_2002_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_Taliban_Insurgent_AKM_2002_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Datsun_Technical_2002_02 : walker_a3_datsun_2_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Datsun Technical 1";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_AK74_2002_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_Taliban_Insurgent_RPG7_2002_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Hilux_Technical_2002_01 : walker_a3_hilux_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux Technical";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_AK74_2002_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_Taliban_Insurgent_PKM_2002_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_Taliban_Insurgent_AKMN_2002_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Taliban_Hilux_Technical_1_2002_01 : walker_a3_v_hilux_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hilux Technical 1";
        side = 0;
        faction = "O_Taliban_2002";
        crew = "O_Taliban_Insurgent_PM63_2002_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_Taliban_Insurgent_RPG7_2002_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_Taliban_Insurgent_AKMS_2002_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 182.144710 on Stable branch
// Generated with ALiVE version 1.6.1.1804271
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class O_Taliban_2002 {
            name = "Taliban (TFR)";

            class Infantry {
                name = "Infantry";

                class o_taliban_infantry_fireteam_1_2002 {
                    name = "Fireteam 1";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                };

                class o_taliban_infantry_fireteam_2_2002 {
                    name = "Fireteam 2";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                };

                class o_taliban_infantry_fireteam_3_2002 {
                    name = "Fireteam 3";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_SMLE_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                };

                class o_taliban_infantry_fireteam_4_2002 {
                    name = "Fireteam 4";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit1 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit3 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                };

                class o_taliban_infantry_fireteam_5_2002 {
                    name = "Fireteam 5";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                };

                class o_taliban_infantry_fireteam_6_2002 {
                    name = "Fireteam 6";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                };

                class o_taliban_infantry_squad_1_2002 {
                    name = "Squad 1";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Taliban_Leader_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_SMLE_2002_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                };

                class o_taliban_infantry_squad_2_2002 {
                    name = "Squad 2";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Taliban_Leader_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_SMLE_2002_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                };

                class o_taliban_infantry_squad_3_2002 {
                    name = "Squad 3";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Taliban_Leader_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_SMLE_2002_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class o_otaliban2002_motorized_hilux_hmg {
                    name = "Hilux HMG";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Technical_DShKM_2002_01";
                    };
                };

                class o_otaliban2002_motorized_hilux_1 {
                    name = "Hilux 1";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Hilux_Technical_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                };

                class o_otaliban2002_motorized_hilux_2 {
                    name = "Hilux 2";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Hilux_Technical_1_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_SMLE_2002_01";
                    };
                };

                class o_otaliban2002_motorized_datsun_1 {
                    name = "Datsun 1";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Datsun_Technical_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                };

                class o_otaliban2002_motorized_datsun_2 {
                    name = "Datsun 2";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Datsun_Technical_2002_02";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                };

                class o_otaliban2002_motorized_s1201_van {
                    name = "S1201 Van";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_S1203_Van_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                };

                class o_otaliban2002_motorized_ural_4320 {
                    name = "Ural-4320";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_Ural_4320_2002_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Taliban_Leader_2002_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_RPG7_2002_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PM63_2002_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_SMLE_2002_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AK74_2002_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMS_2002_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKMN_2002_01";
                    };
                    class Unit10 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_PKM_2002_01";
                    };
                    class Unit11 {
                        position[] = {30,-30,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Taliban_Insurgent_AKM_2002_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

                class o_otaliban2002_armored_t55a {
                    name = "T-55A";
                    side = 0;
                    faction = "O_Taliban_2002";
                    icon = "\A3\ui_f\data\map\markers\nato\o_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Taliban_T55_2002_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};