class CfgPatches {
    class C_AfghanCivilians_2002 {
        units[] = {
            "C_AfghanCivilians_Civilian_2002_03",
            "C_AfghanCivilians_Civilian_2002_02",
            "C_AfghanCivilians_Civilian_2002_01",
            "C_AfghanCivilians_Civilian_2002_04",
            "C_AfghanCivilians_Civilian_2002_05",
            "C_AfghanCivilians_Civilian_2002_06",
            "C_AfghanCivilians_Civilian_2002_07",
            "C_AfghanCivilians_Civilian_2002_08",
            "C_AfghanCivilians_Civilian_2002_09",
            "C_AfghanCivilians_Civilian_2002_10",
            "C_AfghanCivilians_Civilian_2002_11",
            "C_AfghanCivilians_Civilian_2002_12",
            "C_AfghanCivilians_Civilian_2002_13",
            "C_AfghanCivilians_Civilian_2002_14",
            "C_AfghanCivilians_Civilian_2002_15",
            "C_AfghanCivilians_Civilian_Ural_4320_2002_01",
            "C_AfghanCivilians_Civilian_GAZ_Black_2002_01",
            "C_AfghanCivilians_Civilian_Gaz_Blue_2002_01",
            "C_AfghanCivilians_Civilian_Datsun_Blue_2002_01",
            "C_AfghanCivilians_Civilian_Datsun_Grey_2002_01",
            "C_AfghanCivilians_Civilian_Hilux_White_2002_01",
            "C_AfghanCivilians_Civilian_Hilux_Brown_2002_01",
            "C_AfghanCivilians_Civilian_Lada_White_2002_01",
            "C_AfghanCivilians_Civilian_Lada_LM_2002_01",
            "C_AfghanCivilians_Civilian_S1230_Van_2002_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "walker_A3_Vehicles_gaz",
            "walker_A3_Vehicles_datsun",
            "walker_A3_Vehicles_hilux",
            "walker_A3_Vehicles_lada",
            "walker_A3_Vehicles_skodovka",
            "walker_A3_Vehicles_s1203"
        };
        author = "JerkinMerkin";
        authors[] = {"JerkinMerkin"};
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 182.144710 on Stable branch
// Generated with ALiVE version 1.6.1.1804271
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class C_AfghanCivilians_2002 {
        displayName = "Afghan Civilians (TFR)";
        side = 3;
        flag = "\po_main\data\ui\markers\Flag_afg_CO.paa";
        icon = "\po_main\data\ui\markers\Flag_afg_CO.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Civilian {

        class C_AfghanCivilians_2002 {
            name = "Afghan Civilians (TFR)";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class walker_a3_gaz;
    class walker_a3_gaz_OCimport_01 : walker_a3_gaz { scope = 0; class EventHandlers; };
    class walker_a3_gaz_OCimport_02 : walker_a3_gaz_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_gazblue;
    class walker_a3_gazblue_OCimport_01 : walker_a3_gazblue { scope = 0; class EventHandlers; };
    class walker_a3_gazblue_OCimport_02 : walker_a3_gazblue_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_datsun;
    class walker_a3_datsun_OCimport_01 : walker_a3_datsun { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_datsun_OCimport_02 : walker_a3_datsun_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_datsun_2;
    class walker_a3_datsun_2_OCimport_01 : walker_a3_datsun_2 { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_datsun_2_OCimport_02 : walker_a3_datsun_2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_hilux;
    class walker_a3_hilux_OCimport_01 : walker_a3_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_hilux_OCimport_02 : walker_a3_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_v_hilux;
    class walker_a3_v_hilux_OCimport_01 : walker_a3_v_hilux { scope = 0; class EventHandlers; class Turrets; };
    class walker_a3_v_hilux_OCimport_02 : walker_a3_v_hilux_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class walker_a3_lada;
    class walker_a3_lada_OCimport_01 : walker_a3_lada { scope = 0; class EventHandlers; };
    class walker_a3_lada_OCimport_02 : walker_a3_lada_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_skodovka;
    class walker_a3_skodovka_OCimport_01 : walker_a3_skodovka { scope = 0; class EventHandlers; };
    class walker_a3_skodovka_OCimport_02 : walker_a3_skodovka_OCimport_01 { scope = 0; class EventHandlers; };

    class walker_a3_s1203;
    class walker_a3_s1203_OCimport_01 : walker_a3_s1203 { scope = 0; class EventHandlers; };
    class walker_a3_s1203_OCimport_02 : walker_a3_s1203_OCimport_01 { scope = 0; class EventHandlers; };


    class CUP_C_TK_Man_02;
    class CUP_C_TK_Man_02_OCimport_01 : CUP_C_TK_Man_02 { scope = 0; class EventHandlers; };
    class CUP_C_TK_Man_02_OCimport_02 : CUP_C_TK_Man_02_OCimport_01 { class EventHandlers; };


    class C_AfghanCivilians_Civilian_2002_03 : CUP_C_TK_Man_02_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_01";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_Pakol_2_01","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_Pakol_2_01","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CUP_O_TKI_Khet_Partug_01",{}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_Pakol_2_01","CFP_Beard",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_02 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_BlueGrey";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_04","CUP_H_TKI_Lungee_Open_01","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_04","CUP_H_TKI_Lungee_Open_01","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Long_BlueGrey",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_04",{}},{},"CUP_H_TKI_Lungee_Open_01","CUP_TK_NeckScarf",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_01 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_Purple";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_01","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_01","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Long_Purple",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_SkullCap_01","CUP_TK_NeckScarf",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_04 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Short_White";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Pakol_2_01","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Pakol_2_01","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Short_White",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_05",{}},{},"CUP_H_TKI_Pakol_2_01","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };


    class C_AfghanCivilians_Civilian_2002_05 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Short_Creme";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CFP_Lungee_Open_BlueGrey","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CFP_Lungee_Open_BlueGrey","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Short_Creme",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_05",{}},{},"CFP_Lungee_Open_BlueGrey","CFP_Scarfbeard_grey",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_06 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_06";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_03","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_03","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CUP_O_TKI_Khet_Partug_06",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_SkullCap_03","CFP_Scarfbeard_grey",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_07 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Short_Creme";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_Pakol_2_06","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_Pakol_2_06","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Short_Creme",{{"FirstAidKit",1}}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_Pakol_2_06","CUP_TK_NeckScarf",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_08 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_White";

        linkedItems[] = {"CFP_Jacket_SPLM_02","CUP_H_TKI_Pakol_2_06","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CFP_Jacket_SPLM_02","CUP_H_TKI_Pakol_2_06","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Long_White",{}},{"CFP_Jacket_SPLM_02",{}},{},"CUP_H_TKI_Pakol_2_06","CFP_Scarfbeard_grey",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_09 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Short_Grey";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_04","CUP_H_TKI_Pakol_2_05","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_04","CUP_H_TKI_Pakol_2_05","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Short_Grey",{}},{"CUP_V_OI_TKI_Jacket1_04",{}},{},"CUP_H_TKI_Pakol_2_05","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_10 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_01";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_04","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_04","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CUP_O_TKI_Khet_Partug_01",{}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_SkullCap_04","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_11 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_BlueGrey";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_Lungee_Open_02","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_Lungee_Open_02","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Long_BlueGrey",{}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_Lungee_Open_02","CFP_Beard",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };


    class C_AfghanCivilians_Civilian_2002_12 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_Purple";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Pakol_2_06","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Pakol_2_06","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Long_Purple",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_05",{}},{},"CUP_H_TKI_Pakol_2_06","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_13 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CFP_U_KhetPartug_Long_White";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Lungee_Open_02","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Lungee_Open_02","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CFP_U_KhetPartug_Long_White",{{"ACE_fieldDressing",1},{"ACE_packingBandage",1},{"ACE_morphine",1},{"ACE_tourniquet",1}}},{"CUP_V_OI_TKI_Jacket1_05",{}},{},"CUP_H_TKI_Lungee_Open_02","CFP_Scarfbeard_grey",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_14 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_06";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_02","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_06","CUP_H_TKI_SkullCap_02","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CUP_O_TKI_Khet_Partug_06",{}},{"CUP_V_OI_TKI_Jacket1_06",{}},{},"CUP_H_TKI_SkullCap_02","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_2002_15 : C_AfghanCivilians_Civilian_2002_03 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian";
        side = 3;
        faction = "C_AfghanCivilians_2002";

        identityTypes[] = {"Head_TK","CUP_D_Language_TK","G_IRAN_default"};

        uniformClass = "CUP_O_TKI_Khet_Partug_02";

        linkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Pakol_2_01","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"CUP_V_OI_TKI_Jacket1_05","CUP_H_TKI_Pakol_2_01","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"CUP_O_TKI_Khet_Partug_02",{}},{"CUP_V_OI_TKI_Jacket1_05",{}},{},"CUP_H_TKI_Pakol_2_01","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class RHS_Ural_VDV_01;
    class RHS_Ural_VDV_01_OCimport_01 : RHS_Ural_VDV_01 { scope = 0; class EventHandlers; class Turrets; };
    class RHS_Ural_VDV_01_OCimport_02 : RHS_Ural_VDV_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };


    class C_AfghanCivilians_Civilian_Ural_4320_2002_01 : RHS_Ural_VDV_01_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Ural-4320";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "rhs_vdv_driver";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };


    class C_AfghanCivilians_Civilian_GAZ_Black_2002_01 : walker_a3_gaz_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian GAZ (Black)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_03";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Gaz_Blue_2002_01 : walker_a3_gazblue_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Gaz (Blue)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_03";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Datsun_Blue_2002_01 : walker_a3_datsun_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Datsun (Blue)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_06";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "C_AfghanCivilians_Civilian_2002_03"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "C_AfghanCivilians_Civilian_2002_14"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Datsun_Grey_2002_01 : walker_a3_datsun_2_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Datsun (Grey)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "C_AfghanCivilians_Civilian_2002_13"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Hilux_White_2002_01 : walker_a3_hilux_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Hilux (White)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_03";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "C_AfghanCivilians_Civilian_2002_05"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Hilux_Brown_2002_01 : walker_a3_v_hilux_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Hilux (Brown)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_04";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "C_AfghanCivilians_Civilian_2002_14"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "C_AfghanCivilians_Civilian_2002_07"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Lada_White_2002_01 : walker_a3_lada_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Lada (White)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_09";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_Lada_LM_2002_01 : walker_a3_skodovka_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Skodovka";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_05";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_AfghanCivilians_Civilian_S1230_Van_2002_01 : walker_a3_s1203_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian S1230 Van";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_man_1";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };
	
	class CUP_C_TT650_TK_CIV;
    class CUP_C_TT650_TK_CIV_OCimport_01 : CUP_C_TT650_TK_CIV { scope = 0; class EventHandlers; };
    class CUP_C_TT650_TK_CIV_OCimport_02 : CUP_C_TT650_TK_CIV_OCimport_01 { scope = 0; class EventHandlers; };


    class C_CAfghanCivilians2002_Motorcycle_01 : CUP_C_TT650_TK_CIV_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Motorcycle";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_11";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'CUP\WheeledVehicles\CUP_WheeledVehicles_TT650\data\tt650_eciv_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Rusty";

    };

    class CUP_C_Lada_TK2_CIV;
    class CUP_C_Lada_TK2_CIV_OCimport_01 : CUP_C_Lada_TK2_CIV { scope = 0; class EventHandlers; };
    class CUP_C_Lada_TK2_CIV_OCimport_02 : CUP_C_Lada_TK2_CIV_OCimport_01 { scope = 0; class EventHandlers; };


    class C_CAfghanCivilians2002_Civilian_Lada_Taxi_01 : CUP_C_Lada_TK2_CIV_OCimport_02 {
        author = "JerkinMerkin";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Lada (Taxi)";
        side = 3;
        faction = "C_AfghanCivilians_2002";
        crew = "C_AfghanCivilians_Civilian_2002_12";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };
};